### ISSUE TITLE
Homepage - Sidebar : Change font color of the error message from white to red of the contact us.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Serling-Consulting#24]
![22](https://cloud.githubusercontent.com/assets/18256652/16752995/96a1f0c0-4818-11e6-9e9c-c0ea3e7fc1e9.png)

**Comment by a-chiwakanit** [comment]
Fixed

**Comment by iteano** [comment]
Please change the color to red.

![image](https://cloud.githubusercontent.com/assets/18256652/17575975/d9a3d240-5fa0-11e6-95d7-f3a2208d322e.png)
