### ISSUE TITLE
Contact us: Incorrect font family set for the contact details. It should use Asap Regular instead of Yanone Kaffeesatz.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Serling-Consulting#32]
![image](https://cloud.githubusercontent.com/assets/11186313/16753562/56612742-481d-11e6-8175-5b5505510f80.png)

**Comment by a-chiwakanit** [comment]
Fixed

**Comment by iteano** [comment]
Not fixed.

**Comment by iteano** [comment]
Its title text was changed.
![image](https://cloud.githubusercontent.com/assets/18256652/17659434/0d84befa-6305-11e6-9a6a-64a35d8b764d.png)
