### ISSUE TITLE
Latest news: Incorrect font size set for the post title. Font size should be 45px instead of 32px.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Serling-Consulting#45]

**Comment by iteano** [comment]
Not fixed.

![image](https://cloud.githubusercontent.com/assets/18256652/17576884/58f1508c-5faa-11e6-8939-40406cb2aaf7.png)

**Comment by iteano** [comment]
Still not fixed.
![image](https://cloud.githubusercontent.com/assets/18256652/17660281/fa808388-630a-11e6-8eb4-3161b8df5dad.png)
