### ISSUE TITLE
Homepage - Our Projects : View Project button should be dynamic. Cant see any field front backend where this button can be edited.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Serling-Consulting#46]
![30](https://cloud.githubusercontent.com/assets/18256652/16754320/3669929c-4824-11e6-86a6-1381fa50d983.png)

**Comment by a-chiwakanit** [comment]
it's correct. The title, text button, link is auto generate from lasted projects it shouldn't be edited. 

"Our Projects Text Button" and "Our Projects Page Link Button" is dynamic for the button present under projects column
