### ISSUE TITLE
General : Featured image has no set dimension as per design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Serling-Consulting#57]
![image](https://cloud.githubusercontent.com/assets/11186313/16756018/aa088ce8-4834-11e6-8cfb-9ef686ca03cd.png)

![0](https://cloud.githubusercontent.com/assets/18256652/16756886/c34979f0-483a-11e6-89ba-38343bb9936d.png)

**Comment by iteano** [comment]
Not fixed.
